2020-06-10 20:56:30,671 - root - Banned extension: ('captcha_verification', 'test')
2020-06-10 20:56:30,729 - discord.client - PyNaCl is not installed, voice will NOT be supported
2020-06-10 20:56:30,758 - console - loaded bot.cogs.bot_owner_commands
2020-06-10 20:56:30,783 - console - Failed to load cog bot.cogs.security - traceback:['Traceback (most recent call last):\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 608, in _load_from_module_spec\n    setup(self)\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/security.py", line 134, in setup\n    bot.add_cog(Security(bot))\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/security.py", line 19, in __init__\n    self.trusted = self.guild.get_role(constants.trusted_role_id)\n', "AttributeError: 'NoneType' object has no attribute 'get_role'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/__main__.py", line 43, in <module>\n    bot.load_extension(dotted_path)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 653, in load_extension\n    self._load_from_module_spec(spec, name)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 613, in _load_from_module_spec\n    raise errors.ExtensionFailed(key, e) from e\n', "discord.ext.commands.errors.ExtensionFailed: Extension 'bot.cogs.security' raised an error: AttributeError: 'NoneType' object has no attribute 'get_role'\n"]
2020-06-10 20:56:30,784 - asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7578c910>
2020-06-10 20:56:30,792 - console - loaded bot.cogs.help
2020-06-10 20:56:30,833 - console - Failed to load cog bot.cogs.moderation - traceback:['Traceback (most recent call last):\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 608, in _load_from_module_spec\n    setup(self)\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/moderation.py", line 299, in setup\n    bot.add_cog(Admins(bot))\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/moderation.py", line 19, in __init__\n    self.muted_role = self.guild.get_role(constants.muted_role_id)\n', "AttributeError: 'NoneType' object has no attribute 'get_role'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/__main__.py", line 43, in <module>\n    bot.load_extension(dotted_path)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 653, in load_extension\n    self._load_from_module_spec(spec, name)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 613, in _load_from_module_spec\n    raise errors.ExtensionFailed(key, e) from e\n', "discord.ext.commands.errors.ExtensionFailed: Extension 'bot.cogs.moderation' raised an error: AttributeError: 'NoneType' object has no attribute 'get_role'\n"]
2020-06-10 20:56:30,931 - console - loaded bot.cogs.other
2020-06-10 20:56:30,966 - console - loaded bot.cogs.tortoise_api
2020-06-10 20:56:31,476 - console - Failed to load cog bot.cogs.reddit - traceback:['Traceback (most recent call last):\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 608, in _load_from_module_spec\n    setup(self)\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/reddit.py", line 64, in setup\n    bot.add_cog(Reddit(bot))\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/reddit.py", line 14, in __init__\n    user_agent="Tortoise Discord Bot"\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/praw/reddit.py", line 218, in __init__\n    required_message.format(attribute)\n', "praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing. \nThis setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/__main__.py", line 43, in <module>\n    bot.load_extension(dotted_path)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 653, in load_extension\n    self._load_from_module_spec(spec, name)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 613, in _load_from_module_spec\n    raise errors.ExtensionFailed(key, e) from e\n', "discord.ext.commands.errors.ExtensionFailed: Extension 'bot.cogs.reddit' raised an error: MissingRequiredAttributeException: Required configuration setting 'client_id' missing. \nThis setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.\n"]
2020-06-10 20:56:31,483 - console - loaded bot.cogs.fun
2020-06-10 20:56:31,505 - console - loaded bot.cogs.tortoise_server
2020-06-10 20:56:31,526 - console - loaded bot.cogs.tortoise_dm
2020-06-10 20:56:31,548 - bot.cogs.socket_comm - Starting socket comm server...
2020-06-10 20:56:31,550 - bot.cogs.socket_comm - Socket comm server started.
2020-06-10 20:56:31,558 - console - Failed to load cog bot.cogs.socket_comm - traceback:['Traceback (most recent call last):\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 608, in _load_from_module_spec\n    setup(self)\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/socket_comm.py", line 392, in setup\n    bot.add_cog(SocketCommunication(bot))\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/cogs/socket_comm.py", line 83, in __init__\n    self.verified_role = self.tortoise_guild.get_role(constants.verified_role_id)\n', "AttributeError: 'NoneType' object has no attribute 'get_role'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/home/pi/TORTOISE/Tortoise-BOT/bot/__main__.py", line 43, in <module>\n    bot.load_extension(dotted_path)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 653, in load_extension\n    self._load_from_module_spec(spec, name)\n', '  File "/home/pi/.local/share/virtualenvs/Tortoise-BOT-m3dZq2Sm/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 613, in _load_from_module_spec\n    raise errors.ExtensionFailed(key, e) from e\n', "discord.ext.commands.errors.ExtensionFailed: Extension 'bot.cogs.socket_comm' raised an error: AttributeError: 'NoneType' object has no attribute 'get_role'\n"]
2020-06-10 20:56:32,866 - console - loaded bot.cogs.music
2020-06-10 20:56:32,872 - console - loaded bot.cogs.cmd_error_handler
2020-06-10 20:56:32,883 - console - loaded bot.cogs.documentation
2020-06-10 20:56:32,886 - bot.cogs.tortoise_server - Starting rule update loop..
2020-06-10 20:56:32,887 - discord.client - logging in using static token
2020-06-10 20:56:38,150 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-06-10 20:56:38,158 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-06-10 20:56:39,031 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-58bq",{"micros":39039,"calls":["discord-sessions-prd-1-34",{"micros":37280,"calls":["start_session",{"micros":29847,"calls":["api-prd-main-us-east1-2r3v",{"micros":27288,"calls":["get_user",{"micros":3261},"add_authorized_ip",{"micros":1469},"get_guilds",{"micros":1514},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":3945,"calls":[]}]}]}] (Session ID: 11f9a3840ba88145624486ba83712147).
2020-06-10 20:56:43,536 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-06-10 20:56:43,648 - discord.state - Processed a chunk for 493 members in guild ID 577192344529404154.
2020-06-10 20:56:43,657 - bot.cogs.tortoise_server - Rule update loop started!
2020-06-10 20:56:43,659 - console - Successfully logged in as Tortoise Î± ID:603160354360524810 	d.py version: 1.3.3 	Further logging output will go to log file..
2020-06-10 20:56:47,052 - bot.cogs.tortoise_server - Failed to fetch rules from API:Status: 401 Response: {'detail': 'Invalid token.'}
2020-06-10 20:57:39,961 - bot.cogs.bot_owner_commands - security loaded. by 612349409736392928
2020-06-10 20:57:52,353 - bot.cogs.bot_owner_commands - moderation loaded. by 612349409736392928
2020-06-10 20:59:37,234 - discord.client - Cleaning up tasks.
2020-06-10 20:59:37,235 - discord.client - Cleaning up after 5 tasks.
2020-06-10 20:59:37,314 - asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7499e910>
2020-06-10 20:59:37,489 - discord.client - Closing the event loop.
