2020-09-15 18:53:57,399 - discord.client - logging in using static token
2020-09-15 18:54:02,061 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 18:54:02,062 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 18:54:03,101 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-z971",{"micros":90285,"calls":["discord-sessions-prd-2-47",{"micros":87333,"calls":["start_session",{"micros":71048,"calls":["api-prd-main-wm2h",{"micros":65705,"calls":["get_user",{"micros":4260},"add_authorized_ip",{"micros":3227},"get_guilds",{"micros":4701},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":14,"calls":[]},"presence_connect",{"micros":5889,"calls":[]}]}]}] (Session ID: 371623c225dab9fc1f4c17429a1e169b).
2020-09-15 18:54:03,115 - bot.bot - Connection to Discord established.
2020-09-15 18:54:09,752 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 18:54:10,362 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 18:54:10,456 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 18:54:10,458 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 18:54:10,472 - console - loaded bot.cogs.games
2020-09-15 18:54:15,490 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 18:54:17,411 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000017B082ACE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:00:34,878 - discord.gateway - Websocket closed with 1006 (), attempting a reconnect.
2020-09-15 19:00:34,878 - discord.client - Got a request to RESUME the websocket.
2020-09-15 19:00:34,878 - bot.bot - Connection to Discord lost.
2020-09-15 19:00:37,837 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:00:37,839 - discord.gateway - Shard ID None has sent the RESUME payload.
2020-09-15 19:00:38,812 - discord.gateway - Shard ID None has successfully RESUMED session 371623c225dab9fc1f4c17429a1e169b under trace ["gateway-prd-main-r7pp",{"micros":3993,"calls":["discord-sessions-prd-2-47",{"micros":106}]}].
2020-09-15 19:00:54,660 - discord.gateway - Shard ID None has stopped responding to the gateway. Closing and restarting.
2020-09-15 19:03:57,471 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:03:57,472 - discord.client - Cleaning up tasks.
2020-09-15 19:03:57,472 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:03:58,259 - discord.client - Closing the event loop.
2020-09-15 19:04:06,203 - discord.client - logging in using static token
2020-09-15 19:04:09,913 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:04:09,920 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:04:11,162 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-03dm",{"micros":116134,"calls":["discord-sessions-prd-2-48",{"micros":113764,"calls":["start_session",{"micros":101483,"calls":["api-prd-main-n2xf",{"micros":98694,"calls":["get_user",{"micros":4506},"add_authorized_ip",{"micros":6508},"get_guilds",{"micros":4549},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: b53318c81a3b6d9dbc526e4c1e6c48b8).
2020-09-15 19:04:11,177 - bot.bot - Connection to Discord established.
2020-09-15 19:04:16,342 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:04:16,358 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:04:16,362 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 19:04:16,362 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:04:16,371 - console - loaded bot.cogs.games
2020-09-15 19:04:21,678 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:04:22,317 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000002871457CEB0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:05:54,125 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:05:54,125 - discord.client - Cleaning up tasks.
2020-09-15 19:05:54,125 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:05:54,261 - discord.client - Closing the event loop.
2020-09-15 19:06:00,186 - discord.client - logging in using static token
2020-09-15 19:06:04,949 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:06:04,952 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:06:05,919 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-4fd5",{"micros":76212,"calls":["discord-sessions-prd-2-76",{"micros":75330,"calls":["start_session",{"micros":47877,"calls":["api-prd-main-0zbk",{"micros":45274,"calls":["get_user",{"micros":2532},"add_authorized_ip",{"micros":9078},"get_guilds",{"micros":3156},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":13,"calls":[]},"presence_connect",{"micros":21945,"calls":[]}]}]}] (Session ID: cdecef678c3bedff672c9e7cc954dac1).
2020-09-15 19:06:05,935 - bot.bot - Connection to Discord established.
2020-09-15 19:06:07,953 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:06:07,972 - console - loaded bot.cogs.games
2020-09-15 19:06:11,026 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:06:11,476 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:06:11,505 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 19:06:12,399 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:06:13,079 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x00000170FE74CE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:07:47,588 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:07:47,588 - discord.client - Cleaning up tasks.
2020-09-15 19:07:47,588 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:07:47,740 - discord.client - Closing the event loop.
2020-09-15 19:07:56,507 - discord.client - logging in using static token
2020-09-15 19:07:59,994 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:08:01,421 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:08:02,631 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-hr68",{"micros":76933,"calls":["discord-sessions-prd-2-39",{"micros":76067,"calls":["start_session",{"micros":49628,"calls":["api-prd-main-gqt5",{"micros":46890,"calls":["get_user",{"micros":4546},"add_authorized_ip",{"micros":1580},"get_guilds",{"micros":1548},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":17,"calls":[]},"presence_connect",{"micros":12271,"calls":[]}]}]}] (Session ID: 0d9813fbad1e85960ec7a771704681bc).
2020-09-15 19:08:02,647 - bot.bot - Connection to Discord established.
2020-09-15 19:08:04,656 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:08:04,664 - console - loaded bot.cogs.games
2020-09-15 19:08:08,735 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:08:09,067 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:08:09,075 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 19:08:09,094 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:08:09,833 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000012227B2CEB0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:09:05,308 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:09:05,309 - discord.client - Cleaning up tasks.
2020-09-15 19:09:05,309 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:09:05,610 - discord.client - Closing the event loop.
2020-09-15 19:09:13,639 - discord.client - logging in using static token
2020-09-15 19:09:17,508 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:09:17,511 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:09:18,549 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-4fd5",{"micros":69244,"calls":["discord-sessions-prd-2-73",{"micros":68428,"calls":["start_session",{"micros":59498,"calls":["api-prd-main-540b",{"micros":56049,"calls":["get_user",{"micros":3418},"add_authorized_ip",{"micros":7920},"get_guilds",{"micros":10395},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 1aa3a970316f726bb45b4a91f501da62).
2020-09-15 19:09:18,562 - bot.bot - Connection to Discord established.
2020-09-15 19:09:20,570 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:09:20,592 - console - loaded bot.cogs.games
2020-09-15 19:09:25,015 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:09:25,259 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:09:25,261 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:09:25,264 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 19:09:26,801 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:09:27,456 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000001F198AEAE50>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:13:30,275 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:13:30,275 - discord.client - Cleaning up tasks.
2020-09-15 19:13:30,275 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:13:30,418 - discord.client - Closing the event loop.
2020-09-15 19:13:37,174 - discord.client - logging in using static token
2020-09-15 19:13:42,154 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:13:42,156 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:13:43,228 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-bhbv",{"micros":91944,"calls":["discord-sessions-prd-2-6",{"micros":91246,"calls":["start_session",{"micros":70433,"calls":["api-prd-main-wm2h",{"micros":67185,"calls":["get_user",{"micros":8804},"add_authorized_ip",{"micros":1695},"get_guilds",{"micros":1683},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":16,"calls":[]},"presence_connect",{"micros":13162,"calls":[]}]}]}] (Session ID: c2096de273eb9b08303a9e266571e0d8).
2020-09-15 19:13:43,236 - bot.bot - Connection to Discord established.
2020-09-15 19:13:45,236 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:13:45,244 - console - loaded bot.cogs.games
2020-09-15 19:13:48,760 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:13:49,219 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:13:49,222 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 19:13:49,959 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:13:51,337 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000019D22ECCE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:14:45,363 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:14:45,364 - discord.client - Cleaning up tasks.
2020-09-15 19:14:45,364 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:14:45,509 - discord.client - Closing the event loop.
2020-09-15 19:14:51,678 - discord.client - logging in using static token
2020-09-15 19:14:55,415 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:14:55,422 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:14:56,412 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-4ss6",{"micros":71740,"calls":["discord-sessions-prd-2-33",{"micros":70591,"calls":["start_session",{"micros":58569,"calls":["api-prd-main-0t06",{"micros":55916,"calls":["get_user",{"micros":5715},"add_authorized_ip",{"micros":1625},"get_guilds",{"micros":3383},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":9,"calls":[]},"presence_connect",{"micros":1520,"calls":[]}]}]}] (Session ID: 898447d03dfbd10147d652674a66f717).
2020-09-15 19:14:56,428 - bot.bot - Connection to Discord established.
2020-09-15 19:15:02,054 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:15:02,362 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:15:02,783 - discord.state - Processed a chunk for 135 members in guild ID 577192344529404154.
2020-09-15 19:15:02,787 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:15:02,805 - console - loaded bot.cogs.games
2020-09-15 19:15:08,199 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:15:09,532 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000001B7BBC0CE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:17:17,422 - discord.http - We are being rate limited. Retrying in 0.22 seconds. Handled under the bucket "692851221223964822:None:/channels/{channel_id}/messages/{message_id}/reactions"
2020-09-15 19:21:53,508 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:21:53,508 - discord.client - Cleaning up tasks.
2020-09-15 19:21:53,508 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:21:53,749 - discord.client - Closing the event loop.
2020-09-15 19:22:01,174 - discord.client - logging in using static token
2020-09-15 19:22:05,653 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:22:05,655 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:22:06,684 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-q8xc",{"micros":46324,"calls":["discord-sessions-prd-2-41",{"micros":45100,"calls":["start_session",{"micros":29713,"calls":["api-prd-main-315z",{"micros":27265,"calls":["get_user",{"micros":2421},"add_authorized_ip",{"micros":1696},"get_guilds",{"micros":1579},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":8,"calls":[]},"presence_connect",{"micros":12730,"calls":[]}]}]}] (Session ID: 651f344c0857dd06abedc6b28dcf440a).
2020-09-15 19:22:06,699 - bot.bot - Connection to Discord established.
2020-09-15 19:22:13,363 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:22:14,119 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:22:14,122 - discord.state - Processed a chunk for 136 members in guild ID 577192344529404154.
2020-09-15 19:22:14,124 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:22:14,132 - console - loaded bot.cogs.games
2020-09-15 19:22:18,690 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:22:19,413 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000024F9094AE50>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:24:03,316 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:24:03,316 - discord.client - Cleaning up tasks.
2020-09-15 19:24:03,317 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:24:03,460 - discord.client - Closing the event loop.
2020-09-15 19:25:06,090 - discord.client - logging in using static token
2020-09-15 19:25:09,642 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:25:09,649 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:25:10,680 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-q160",{"micros":66366,"calls":["discord-sessions-prd-1-14",{"micros":65091,"calls":["start_session",{"micros":37322,"calls":["api-prd-main-3z66",{"micros":32719,"calls":["get_user",{"micros":4887},"add_authorized_ip",{"micros":1645},"get_guilds",{"micros":1478},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":15624,"calls":[]}]}]}] (Session ID: ecfee904ab0860140a48b370da1c7fd2).
2020-09-15 19:25:10,695 - bot.bot - Connection to Discord established.
2020-09-15 19:25:16,878 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:25:17,122 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:25:17,199 - discord.state - Processed a chunk for 136 members in guild ID 577192344529404154.
2020-09-15 19:25:17,200 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:25:17,218 - console - loaded bot.cogs.games
2020-09-15 19:25:21,646 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:25:22,992 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000001F198A3CEE0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:28:03,445 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:28:03,445 - discord.client - Cleaning up tasks.
2020-09-15 19:28:03,445 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:28:03,645 - discord.client - Closing the event loop.
2020-09-15 19:30:49,349 - discord.client - logging in using static token
2020-09-15 19:30:52,963 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:30:52,971 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:30:54,194 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-r7pp",{"micros":205774,"calls":["discord-sessions-prd-2-24",{"micros":204766,"calls":["start_session",{"micros":173248,"calls":["api-prd-main-2gnm",{"micros":156316,"calls":["get_user",{"micros":9358},"add_authorized_ip",{"micros":24396},"get_guilds",{"micros":8003},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":14327,"calls":[]}]}]}] (Session ID: 217cb70a1e565de6e8a8333a7125e7cb).
2020-09-15 19:30:54,205 - bot.bot - Connection to Discord established.
2020-09-15 19:30:56,199 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:30:56,220 - console - loaded bot.cogs.games
2020-09-15 19:31:00,596 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:31:01,191 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:31:01,222 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:31:01,226 - discord.state - Processed a chunk for 136 members in guild ID 577192344529404154.
2020-09-15 19:31:02,116 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:31:03,474 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000002CDB061CEE0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:32:01,132 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:32:01,133 - discord.client - Cleaning up tasks.
2020-09-15 19:32:01,133 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:32:01,303 - discord.client - Closing the event loop.
2020-09-15 19:32:10,215 - discord.client - logging in using static token
2020-09-15 19:32:14,271 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:32:14,278 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:32:15,634 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-4ss6",{"micros":73866,"calls":["discord-sessions-prd-2-57",{"micros":72047,"calls":["start_session",{"micros":59714,"calls":["api-prd-main-01kq",{"micros":55035,"calls":["get_user",{"micros":2729},"add_authorized_ip",{"micros":2902},"get_guilds",{"micros":4846},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":5,"calls":[]},"presence_connect",{"micros":0,"calls":[]}]}]}] (Session ID: 4e82c92056e45ddea93bac5e4f9461c7).
2020-09-15 19:32:15,648 - bot.bot - Connection to Discord established.
2020-09-15 19:32:17,661 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:32:17,686 - console - loaded bot.cogs.games
2020-09-15 19:32:22,158 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:32:22,160 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:32:22,915 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:32:22,949 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:32:22,955 - discord.state - Processed a chunk for 136 members in guild ID 577192344529404154.
2020-09-15 19:32:24,438 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000002595626CEE0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:32:55,404 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:32:55,404 - discord.client - Cleaning up tasks.
2020-09-15 19:32:55,404 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:32:55,652 - discord.client - Closing the event loop.
2020-09-15 19:33:04,608 - discord.client - logging in using static token
2020-09-15 19:33:08,042 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:33:08,045 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:33:09,075 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-3v8x",{"micros":102039,"calls":["discord-sessions-prd-2-10",{"micros":100877,"calls":["start_session",{"micros":79112,"calls":["api-prd-main-s64z",{"micros":76740,"calls":["get_user",{"micros":6119},"add_authorized_ip",{"micros":9852},"get_guilds",{"micros":7707},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":22,"calls":[]},"presence_connect",{"micros":4658,"calls":[]}]}]}] (Session ID: 23100f571fadbf02c2edca26c3196991).
2020-09-15 19:33:09,092 - bot.bot - Connection to Discord established.
2020-09-15 19:33:11,105 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:33:11,129 - console - loaded bot.cogs.games
2020-09-15 19:33:14,925 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:33:14,964 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:33:14,968 - discord.state - Processed a chunk for 136 members in guild ID 577192344529404154.
2020-09-15 19:33:16,047 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:33:16,749 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000024EC3DBCF10>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:37:55,230 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:37:55,230 - discord.client - Cleaning up tasks.
2020-09-15 19:37:55,230 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:37:55,871 - discord.client - All tasks finished cancelling.
2020-09-15 19:37:55,871 - discord.client - Closing the event loop.
2020-09-15 19:38:01,540 - discord.client - logging in using static token
2020-09-15 19:38:09,292 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:38:09,299 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:38:10,784 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-1g7b",{"micros":78659,"calls":["discord-sessions-prd-2-76",{"micros":77389,"calls":["start_session",{"micros":69066,"calls":["api-prd-main-0z71",{"micros":66464,"calls":["get_user",{"micros":5276},"add_authorized_ip",{"micros":2703},"get_guilds",{"micros":5032},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: b461dad34a8dcd7d88a51678a781ab24).
2020-09-15 19:38:10,800 - bot.bot - Connection to Discord established.
2020-09-15 19:38:12,793 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:38:12,814 - console - loaded bot.cogs.games
2020-09-15 19:38:14,857 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:38:16,066 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:38:16,069 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:38:16,072 - discord.state - Processed a chunk for 136 members in guild ID 577192344529404154.
2020-09-15 19:38:18,107 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:38:19,465 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000023010D9CEB0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:42:04,877 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:42:04,877 - discord.client - Cleaning up tasks.
2020-09-15 19:42:04,877 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:42:05,061 - discord.client - Closing the event loop.
2020-09-15 19:42:13,113 - discord.client - logging in using static token
2020-09-15 19:42:18,257 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:42:18,265 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:42:19,551 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-gph3",{"micros":354099,"calls":["discord-sessions-prd-2-60",{"micros":353046,"calls":["start_session",{"micros":347121,"calls":["api-prd-main-w580",{"micros":344499,"calls":["get_user",{"micros":2186},"add_authorized_ip",{"micros":1581},"get_guilds",{"micros":1568},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":0,"calls":[]}]}]}] (Session ID: 79f36e5f191b8abbdb8c70e00b917b3f).
2020-09-15 19:42:19,568 - bot.bot - Connection to Discord established.
2020-09-15 19:42:25,758 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:42:26,142 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:42:26,148 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 19:42:26,149 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:42:26,156 - console - loaded bot.cogs.games
2020-09-15 19:42:30,581 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:42:31,297 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000023A702ECE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:51:54,821 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:51:54,821 - discord.client - Cleaning up tasks.
2020-09-15 19:51:54,821 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:51:55,009 - discord.client - Closing the event loop.
2020-09-15 19:52:01,466 - discord.client - logging in using static token
2020-09-15 19:52:05,290 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:52:05,292 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:52:07,611 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-8wk4",{"micros":81383,"calls":["discord-sessions-prd-2-79",{"micros":79430,"calls":["start_session",{"micros":50288,"calls":["api-prd-main-q99d",{"micros":43462,"calls":["get_user",{"micros":5975},"add_authorized_ip",{"micros":1179},"get_guilds",{"micros":1927},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":5,"calls":[]},"presence_connect",{"micros":26286,"calls":[]}]}]}] (Session ID: ff9d722b4738ff746e136a690e048056).
2020-09-15 19:52:07,634 - bot.bot - Connection to Discord established.
2020-09-15 19:52:09,630 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:52:09,645 - console - Failed to load cog bot.cogs.games - traceback:['Traceback (most recent call last):\n', '  File "C:\\Users\\Vaishnav\\.virtualenvs\\Tortoise-BOT-NdGTmAqy\\lib\\site-packages\\discord\\ext\\commands\\bot.py", line 596, in _load_from_module_spec\n    spec.loader.exec_module(lib)\n', '  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "C:\\Users\\Vaishnav\\Projects\\Tortoise-BOT\\bot\\cogs\\games.py", line 4, in <module>\n    from bot.cogs.utils.embed_handler import simple_embed, black_jack_embed\n', '  File "C:\\Users\\Vaishnav\\Projects\\Tortoise-BOT\\bot\\cogs\\utils\\embed_handler.py", line 330\n', '    embed.add_field(name="Your hand", value=f"{card_string}\\n•Value:{player.card_value})\n', '                                                                                       ^\n', 'SyntaxError: EOL while scanning string literal\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\Vaishnav\\Projects\\Tortoise-BOT\\bot\\bot.py", line 69, in load_extensions\n    self.load_extension(dotted_path)\n', '  File "C:\\Users\\Vaishnav\\.virtualenvs\\Tortoise-BOT-NdGTmAqy\\lib\\site-packages\\discord\\ext\\commands\\bot.py", line 653, in load_extension\n    self._load_from_module_spec(spec, name)\n', '  File "C:\\Users\\Vaishnav\\.virtualenvs\\Tortoise-BOT-NdGTmAqy\\lib\\site-packages\\discord\\ext\\commands\\bot.py", line 599, in _load_from_module_spec\n    raise errors.ExtensionFailed(key, e) from e\n', "discord.ext.commands.errors.ExtensionFailed: Extension 'bot.cogs.games' raised an error: SyntaxError: EOL while scanning string literal (embed_handler.py, line 330)\n"]
2020-09-15 19:52:15,630 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:52:16,498 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:52:17,340 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:52:17,783 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:52:17,786 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 19:52:18,152 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000001D57E9CCF10>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:53:31,044 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:53:31,044 - discord.client - Cleaning up tasks.
2020-09-15 19:53:31,045 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:53:31,212 - discord.client - Closing the event loop.
2020-09-15 19:53:38,136 - discord.client - logging in using static token
2020-09-15 19:53:41,852 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:53:41,858 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:53:42,885 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-fgqk",{"micros":65988,"calls":["discord-sessions-prd-2-14",{"micros":62805,"calls":["start_session",{"micros":49702,"calls":["api-prd-main-5w4c",{"micros":44282,"calls":["get_user",{"micros":3161},"add_authorized_ip",{"micros":3468},"get_guilds",{"micros":1579},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 9b3a678c2e3d53493f0d6e2bf1ea266c).
2020-09-15 19:53:42,901 - bot.bot - Connection to Discord established.
2020-09-15 19:53:44,890 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:53:44,906 - console - Failed to load cog bot.cogs.games - traceback:['Traceback (most recent call last):\n', '  File "C:\\Users\\Vaishnav\\.virtualenvs\\Tortoise-BOT-NdGTmAqy\\lib\\site-packages\\discord\\ext\\commands\\bot.py", line 596, in _load_from_module_spec\n    spec.loader.exec_module(lib)\n', '  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "C:\\Users\\Vaishnav\\Projects\\Tortoise-BOT\\bot\\cogs\\games.py", line 4, in <module>\n    from bot.cogs.utils.embed_handler import simple_embed, black_jack_embed\n', '  File "C:\\Users\\Vaishnav\\Projects\\Tortoise-BOT\\bot\\cogs\\utils\\embed_handler.py", line 330\n', '    embed.add_field(name="Your hand", value=f"{card_string}\\n•Value:{player.card_value})\n', '                                                                                       ^\n', 'SyntaxError: EOL while scanning string literal\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\Vaishnav\\Projects\\Tortoise-BOT\\bot\\bot.py", line 69, in load_extensions\n    self.load_extension(dotted_path)\n', '  File "C:\\Users\\Vaishnav\\.virtualenvs\\Tortoise-BOT-NdGTmAqy\\lib\\site-packages\\discord\\ext\\commands\\bot.py", line 653, in load_extension\n    self._load_from_module_spec(spec, name)\n', '  File "C:\\Users\\Vaishnav\\.virtualenvs\\Tortoise-BOT-NdGTmAqy\\lib\\site-packages\\discord\\ext\\commands\\bot.py", line 599, in _load_from_module_spec\n    raise errors.ExtensionFailed(key, e) from e\n', "discord.ext.commands.errors.ExtensionFailed: Extension 'bot.cogs.games' raised an error: SyntaxError: EOL while scanning string literal (embed_handler.py, line 330)\n"]
2020-09-15 19:53:49,927 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:53:50,790 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000021BAF9FCEB0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:53:51,085 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:53:51,347 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:53:51,366 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:53:51,698 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 19:54:23,605 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:54:23,605 - discord.client - Cleaning up tasks.
2020-09-15 19:54:23,605 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:54:23,789 - discord.client - Closing the event loop.
2020-09-15 19:54:29,169 - discord.client - logging in using static token
2020-09-15 19:54:34,166 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:54:34,168 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:54:35,203 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-07k7",{"micros":67998,"calls":["discord-sessions-prd-2-45",{"micros":65664,"calls":["start_session",{"micros":47580,"calls":["api-prd-main-xlfj",{"micros":44533,"calls":["get_user",{"micros":5742},"add_authorized_ip",{"micros":1539},"get_guilds",{"micros":1761},"coros_wait",{"micros":3}]}]},"guilds_connect",{"micros":9,"calls":[]},"presence_connect",{"micros":5971,"calls":[]}]}]}] (Session ID: 9545396bdf8b253714b445ecd326c2dc).
2020-09-15 19:54:35,218 - bot.bot - Connection to Discord established.
2020-09-15 19:54:37,213 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:54:37,234 - console - loaded bot.cogs.games
2020-09-15 19:54:40,867 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:54:41,389 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:54:41,879 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:54:41,884 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 19:54:42,747 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:54:43,445 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x0000023FE5FDCEB0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:55:41,876 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:55:41,876 - discord.client - Cleaning up tasks.
2020-09-15 19:55:41,876 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:55:42,472 - discord.client - All tasks finished cancelling.
2020-09-15 19:55:42,472 - discord.client - Closing the event loop.
2020-09-15 19:56:05,942 - discord.client - logging in using static token
2020-09-15 19:56:11,897 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:56:11,900 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:56:12,994 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-s26j",{"micros":90865,"calls":["discord-sessions-prd-2-89",{"micros":87689,"calls":["start_session",{"micros":73260,"calls":["api-prd-main-vv0w",{"micros":70410,"calls":["get_user",{"micros":6910},"add_authorized_ip",{"micros":5503},"get_guilds",{"micros":3672},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":5,"calls":[]},"presence_connect",{"micros":5471,"calls":[]}]}]}] (Session ID: 0e827c8f659aebcbd70b76837216d2d9).
2020-09-15 19:56:13,010 - bot.bot - Connection to Discord established.
2020-09-15 19:56:15,021 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:56:15,044 - console - loaded bot.cogs.games
2020-09-15 19:56:20,159 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:56:21,320 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:56:22,556 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x00000161C0EFCE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:56:22,904 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:56:23,431 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:56:23,599 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 19:57:11,737 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 19:57:11,737 - discord.client - Cleaning up tasks.
2020-09-15 19:57:11,737 - discord.client - Cleaning up after 4 tasks.
2020-09-15 19:57:12,324 - discord.client - All tasks finished cancelling.
2020-09-15 19:57:12,324 - discord.client - Closing the event loop.
2020-09-15 19:57:16,885 - discord.client - logging in using static token
2020-09-15 19:57:20,486 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 19:57:20,492 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 19:57:21,594 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-khp7",{"micros":135955,"calls":["discord-sessions-prd-1-8",{"micros":132932,"calls":["start_session",{"micros":126107,"calls":["api-prd-main-qqxz",{"micros":122737,"calls":["get_user",{"micros":5532},"add_authorized_ip",{"micros":7590},"get_guilds",{"micros":11560},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":7,"calls":[]},"presence_connect",{"micros":619,"calls":[]}]}]}] (Session ID: 4d60e3e1fc92447935bdf22267f1462d).
2020-09-15 19:57:21,611 - bot.bot - Connection to Discord established.
2020-09-15 19:57:23,615 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 19:57:23,635 - console - loaded bot.cogs.bot_owner_commands
2020-09-15 19:57:23,643 - console - loaded bot.cogs.games
2020-09-15 19:57:28,818 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 19:57:28,981 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:57:29,634 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 19:57:29,637 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 19:57:29,843 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 19:57:30,559 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000002832E20ADF0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 19:57:42,793 - bot.cogs.bot_owner_commands - games unloaded. by 612349409736392928
2020-09-15 19:57:46,643 - bot.cogs.bot_owner_commands - games loaded. by 612349409736392928
2020-09-15 20:00:28,471 - bot.cogs.bot_owner_commands - games unloaded. by 612349409736392928
2020-09-15 20:00:31,096 - bot.cogs.bot_owner_commands - games loaded. by 612349409736392928
2020-09-15 20:01:42,538 - bot.cogs.bot_owner_commands - games unloaded. by 612349409736392928
2020-09-15 20:01:45,114 - bot.cogs.bot_owner_commands - games loaded. by 612349409736392928
2020-09-15 20:02:00,981 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 20:02:00,981 - discord.client - Cleaning up tasks.
2020-09-15 20:02:00,981 - discord.client - Cleaning up after 4 tasks.
2020-09-15 20:02:01,188 - discord.client - Closing the event loop.
2020-09-15 20:02:06,766 - discord.client - logging in using static token
2020-09-15 20:02:10,468 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 20:02:10,548 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 20:02:11,603 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-s26j",{"micros":118724,"calls":["discord-sessions-prd-2-40",{"micros":114439,"calls":["start_session",{"micros":85935,"calls":["api-prd-main-6d68",{"micros":82916,"calls":["get_user",{"micros":4205},"add_authorized_ip",{"micros":8618},"get_guilds",{"micros":10603},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":6,"calls":[]},"presence_connect",{"micros":6314,"calls":[]}]}]}] (Session ID: 4a23f0b3e20a69d9f7ea883aeefd9e77).
2020-09-15 20:02:11,620 - bot.bot - Connection to Discord established.
2020-09-15 20:02:13,646 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 20:02:13,667 - console - loaded bot.cogs.bot_owner_commands
2020-09-15 20:02:13,672 - console - loaded bot.cogs.games
2020-09-15 20:02:18,193 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:02:18,624 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 20:02:19,084 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 20:02:19,154 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:02:19,391 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 20:02:19,777 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000002012A5AAE50>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 20:06:29,021 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 20:06:29,021 - discord.client - Cleaning up tasks.
2020-09-15 20:06:29,021 - discord.client - Cleaning up after 4 tasks.
2020-09-15 20:06:29,261 - discord.client - Closing the event loop.
2020-09-15 20:06:34,504 - discord.client - logging in using static token
2020-09-15 20:06:38,104 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 20:06:38,143 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 20:06:39,192 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-zv73",{"micros":107355,"calls":["discord-sessions-prd-2-73",{"micros":105947,"calls":["start_session",{"micros":73060,"calls":["api-prd-main-2cgg",{"micros":70894,"calls":["get_user",{"micros":7470},"add_authorized_ip",{"micros":3016},"get_guilds",{"micros":2887},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":10,"calls":[]},"presence_connect",{"micros":12080,"calls":[]}]}]}] (Session ID: cfae173852fdfb0780e9522673416ca5).
2020-09-15 20:06:39,205 - bot.bot - Connection to Discord established.
2020-09-15 20:06:41,229 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 20:06:41,250 - console - loaded bot.cogs.bot_owner_commands
2020-09-15 20:06:41,260 - console - loaded bot.cogs.games
2020-09-15 20:06:45,588 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:06:46,157 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:06:46,204 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 20:06:46,865 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 20:06:48,386 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x00000254DED1AE50>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 20:06:54,492 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 20:06:54,492 - discord.client - Cleaning up tasks.
2020-09-15 20:06:54,493 - discord.client - Cleaning up after 4 tasks.
2020-09-15 20:06:54,683 - discord.client - Closing the event loop.
2020-09-15 20:08:56,895 - discord.client - logging in using static token
2020-09-15 20:09:00,856 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 20:09:00,863 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 20:09:01,979 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-0cct",{"micros":102323,"calls":["discord-sessions-prd-2-28",{"micros":100554,"calls":["start_session",{"micros":67532,"calls":["api-prd-main-knsr",{"micros":62592,"calls":["get_user",{"micros":4533},"add_authorized_ip",{"micros":2925},"get_guilds",{"micros":5901},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":5,"calls":[]},"presence_connect",{"micros":27311,"calls":[]}]}]}] (Session ID: fb7f9c967792064e90980ee0e75e60d9).
2020-09-15 20:09:01,995 - bot.bot - Connection to Discord established.
2020-09-15 20:09:03,990 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 20:09:04,009 - console - loaded bot.cogs.bot_owner_commands
2020-09-15 20:09:04,015 - console - loaded bot.cogs.games
2020-09-15 20:09:09,646 - discord.state - Somehow timed out waiting for chunks.
2020-09-15 20:09:10,064 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:09:11,243 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:09:11,365 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 20:09:11,490 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 20:09:12,150 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x000001D7522ECEE0>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 20:17:06,100 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 20:17:06,100 - discord.client - Cleaning up tasks.
2020-09-15 20:17:06,100 - discord.client - Cleaning up after 4 tasks.
2020-09-15 20:17:06,284 - discord.client - Closing the event loop.
2020-09-15 20:17:13,845 - discord.client - logging in using static token
2020-09-15 20:17:17,436 - discord.gateway - Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2020-09-15 20:17:17,437 - discord.gateway - Shard ID None has sent the IDENTIFY payload.
2020-09-15 20:17:18,536 - discord.gateway - Shard ID None has connected to Gateway: ["gateway-prd-main-c9tc",{"micros":82093,"calls":["discord-sessions-prd-2-72",{"micros":79335,"calls":["start_session",{"micros":63912,"calls":["api-prd-main-0zbk",{"micros":60398,"calls":["get_user",{"micros":5309},"add_authorized_ip",{"micros":9186},"get_guilds",{"micros":4359},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":8,"calls":[]},"presence_connect",{"micros":3158,"calls":[]}]}]}] (Session ID: deb0f5ae575409b372ec80688e3b8a1a).
2020-09-15 20:17:18,548 - bot.bot - Connection to Discord established.
2020-09-15 20:17:23,803 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:17:24,674 - discord.state - Processed a chunk for 1000 members in guild ID 577192344529404154.
2020-09-15 20:17:24,956 - discord.state - Processed a chunk for 137 members in guild ID 577192344529404154.
2020-09-15 20:17:24,956 - console - Successfully logged in as gambling bot ID:729824279990108222 	d.py version: 1.3.4 	Further logging output will go to log file..
2020-09-15 20:17:24,963 - console - loaded bot.cogs.bot_owner_commands
2020-09-15 20:17:24,967 - console - loaded bot.cogs.games
2020-09-15 20:17:29,581 - bot.bot - on_ready event error exception!
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

2020-09-15 20:17:30,525 - asyncio - _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_ready coro=<bound method Bot.on_ready of <bot.bot.Bot object at 0x00000237BDE4CE80>> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 43, in on_ready
    await self.on_first_ready()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 49, in on_first_ready
    await self.reload_tortoise_meta_cache()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 55, in reload_tortoise_meta_cache
    self.tortoise_meta_cache = await self.api_client.get_server_meta()
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 128, in get_server_meta
    return await self.get(f"server/meta/{guild_id}/")
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 62, in get
    await self.raise_for_status(resp)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\api_client.py", line 55, in raise_for_status
    raise ResponseCodeError(response=response, response_json=response_json)
bot.api_client.ResponseCodeError: Status: 401 Response: {'detail': 'Invalid token.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\client.py", line 317, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 90, in on_error
    await self.log_error(msg)
  File "C:\Users\Vaishnav\Projects\Tortoise-BOT\bot\bot.py", line 101, in log_error
    await error_log_channel.send(f"```Num {count+1}/{len(split_messages)}:\n{message}```")
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Users\Vaishnav\.virtualenvs\Tortoise-BOT-NdGTmAqy\lib\site-packages\discord\http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2020-09-15 20:18:28,207 - bot.cogs.bot_owner_commands - games reloaded. by 612349409736392928
2020-09-15 20:19:36,410 - discord.client - Received signal to terminate bot and event loop.
2020-09-15 20:19:36,410 - discord.client - Cleaning up tasks.
2020-09-15 20:19:36,410 - discord.client - Cleaning up after 4 tasks.
2020-09-15 20:19:36,556 - discord.client - Closing the event loop.
